import { Footer } from "@/components/footer/Footer";
import Menu from "@/components/menu/Menu";
import NavBar from "@/components/navBar/NavBar";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const openSans = Open_Sans({
    subsets: ["latin"],
    variable: "--font-open-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${openSans.variable} bg-[#2A3447] text-white flex flex-col min-h-screen`}
            >
                <header>
                    <NavBar />
                </header>
                <main className="flex flex-1">
                    <section className="flex md:p-5 flex-1">
                        <Menu />
                        {children}
                    </section>
                </main>
                <footer>
                    <Footer />
                </footer>
            </body>
        </html>
    );
}
